export const CART_ACTION={
    ADD_ITEM:"ADD_CART",
    UPDATE_ITEM:"UPDATE_ITEM",
    DELETE_ITEM:"DELETE_ITEM",

    ADD_ITEM_QUANTITY:"ADD_ITEM_QUANTITY",
    DEDUCT_ITEM_QUANTITY:"DEDUCT_ITEM_QUANTITY",

}